version: '3'

services:
  # 数据库服务
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mmdfd
      MYSQL_USER: mmdfd_user
      MYSQL_PASSWORD: mmdfd_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mmdfd_network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mmdfd
      - DATABASE_USER=mmdfd_user
      - DATABASE_PASSWORD=mmdfd_password
      - SECRET_KEY=your_django_secret_key
      - DEBUG=false
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - mmdfd_network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always
    ports:
      - "8080:80"
    networks:
      - mmdfd_network

networks:
  mmdfd_network:
    driver: bridge

volumes:
  mysql_data: 