# Generated by Django 4.2.9 on 2025-04-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', 'create_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super', '超级管理员'), ('content', '内容管理员'), ('user', '用户管理员')], max_length=20, null=True, verbose_name='管理员角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
    ]
